import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Write every design token out as a theme file, so the UI can be designed
 * against the running client instead of against a rebuild.
 *
 * A theme is applied last in the cascade and the themes folder is watched
 * (`main/themes.ts`), so a token overridden in that file lands in the game the
 * moment you save — no reload, no restart, no `npm start`. Which makes a file
 * holding all of them a live editor for the client's whole look:
 *
 *   1. npm run tokens:dev
 *   2. npm start, then F1 -> Client -> Themes -> dev-tokens.css
 *   3. edit the file next to the game; every save shows up immediately
 *   4. paste what you kept into src/shared/ui/tokens.ts
 *
 * Generated rather than hand-written so it cannot drift: every token is here
 * at its current value, and the script fails if it emits fewer than the source
 * defines. Re-run it after adding a token.
 *
 * The one thing it can't reach is the standalone ranked queue window, which is
 * its own document with no theme loader. Its `--nm-rq-*` group is written out
 * for reference, but editing those lines does nothing until they go into
 * tokens.ts.
 */

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokensFile = join(root, 'src/shared/ui/tokens.ts');
const brandingFile = join(root, 'src/shared/branding.ts');

/**
 * Read a source file with line endings normalised.
 *
 * `core.autocrlf` is on for this repo, so a Windows checkout has CRLF in the
 * working tree while every pattern below anchors on a bare newline. Without
 * this the script matches nothing and the guard further down refuses to write,
 * which is how it was found: `npm run tokens:dev` reported "emitted 0 of 161
 * tokens" on a clean Windows clone.
 */
const read = (path) => readFileSync(path, 'utf8').replace(/\r\n/g, '\n');

const src = read(tokensFile);

/** Values kept as JS constants and interpolated into a token. */
const constants = new Map(
  [...src.matchAll(/export const (\w+) = '([^']+)'/g)].map((m) => [m[1], m[2]]),
);
const fill = (line) => line.replace(/\$\{(\w+)\}/g, (all, name) => constants.get(name) ?? all);

/** Each `const NAME = ` block of tokens, with the comment above it. */
const groups = [...src.matchAll(/const (\w+) = `\n([\s\S]*?)`;/g)].map((match) => {
  const before = src.slice(0, match.index);
  const start = before.lastIndexOf('/**');
  const doc =
    start === -1 ? '' : before.slice(start).replace(/^\/\*\*/, '').replace(/\*\/[\s\S]*$/, '');
  return {
    name: match[1].replace(/_/g, ' ').toLowerCase(),
    // First sentence only; the full reasoning stays in tokens.ts.
    summary: doc.replace(/^\s*\*\s?/gm, '').replace(/`/g, '').trim().split(/\.\s/)[0]
      .replace(/\s+/g, ' '),
    lines: match[2].trim().split('\n').map((line) => fill(line.trim())),
  };
});

const out = [
  '/*',
  ' * NM/NEZ design tokens, live.',
  ' *',
  ' * Generated by `npm run tokens:dev` from src/shared/ui/tokens.ts. Every token',
  ' * at its current value, so changing one here changes it everywhere the client',
  ' * uses it. Save and the game picks it up straight away - this folder is',
  ' * watched. When you like what you see, paste the lines you changed back into',
  ' * tokens.ts and they become the default.',
  ' *',
  ' * Not reachable from here: the standalone ranked queue window, which is a',
  ' * separate document with no theme loader. Its --nm-rq-* group is below for',
  ' * reference only.',
  ' */',
  ':root {',
];

for (const group of groups) {
  out.push('', `  /* ─── ${group.name} */`);
  if (group.summary) out.push(`  /* ${group.summary}. */`);
  out.push(...group.lines.map((line) => `  ${line}`));
}
out.push('}', '');

const text = out.join('\n');

// A generated file that silently drops tokens is worse than no file at all.
const declared = (src.replace(/\/\*[\s\S]*?\*\//g, '').match(/--nm-[a-z0-9-]+\s*:/g) ?? []).length;
const written = (text.match(/^\s+--nm-[a-z0-9-]+\s*:/gm) ?? []).length;
if (written !== declared || text.includes('${')) {
  console.error(`dev-tokens: emitted ${written} of ${declared} tokens, refusing to write`);
  process.exit(1);
}

/** Same folder the client reads, derived rather than typed out twice. */
function themesDir() {
  const dirName = /userDataDirName: '([^']+)'/.exec(read(brandingFile))?.[1];
  if (dirName === undefined) throw new Error('could not read userDataDirName from branding.ts');

  const base =
    process.platform === 'win32'
      ? (process.env['APPDATA'] ?? join(homedir(), 'AppData', 'Roaming'))
      : join(homedir(), '.config');
  return join(base, dirName, 'swap', 'themes');
}

const target = process.argv[2] ?? join(themesDir(), 'dev-tokens.css');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, text, 'utf8');

console.log(`dev-tokens: ${written} tokens in ${groups.length} groups`);
console.log(`            ${target}`);
console.log('            pick it under F1 -> Client -> Themes, then edit and save');
